- name: Ubuntu Init Playbook
  hosts: localhost
  become: yes

  tasks:
    - name: git user.email
      git_config:
        name: user.email
        scope: global
        value: "curelesss@gmail.com"
      tags:
      - git
    - name: git user.name
      git_config:
        name: user.name
        scope: global
        value: "curelesss"
      tags:
      - git
